# Generated by Django 5.1.1 on 2024-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bass',
            name='brand',
            field=models.CharField(default='Fender', max_length=50),
        ),
        migrations.AddField(
            model_name='bass',
            name='color',
            field=models.CharField(default='Negro', max_length=50),
        ),
        migrations.AddField(
            model_name='bass',
            name='description',
            field=models.CharField(default='Jaguar Bass Vintage Modified. 4 Cuerdas. Activo. Color Sunburst. Pickguard negro liso. Micrófonos, cuerdas y clavijeras originales.', max_length=150),
        ),
        migrations.AddField(
            model_name='bass',
            name='model',
            field=models.CharField(default='Vintage Modified Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='guitar',
            name='brand',
            field=models.CharField(default='Epiphone', max_length=50),
        ),
        migrations.AddField(
            model_name='guitar',
            name='color',
            field=models.CharField(default='Caoba', max_length=50),
        ),
        migrations.AddField(
            model_name='guitar',
            name='description',
            field=models.CharField(default='Epiphone fabrica instrumentos para todos los estilos de música popular, con espíritu pionero y de invención. El valor de sus productos resalta por su calidad e innovación.', max_length=150),
        ),
        migrations.AddField(
            model_name='guitar',
            name='model',
            field=models.CharField(default='SG Standard 60s', max_length=50),
        ),
        migrations.AlterField(
            model_name='bass',
            name='name',
            field=models.CharField(default='Fender Squier Jaguar', max_length=50),
        ),
        migrations.AlterField(
            model_name='bass',
            name='price',
            field=models.IntegerField(verbose_name=900000),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='pedrolampo50@gmail.com'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Pedro', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(default='Sanchez', max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='name',
            field=models.CharField(default='Epiphone Original Collection SG Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(verbose_name=1500000),
        ),
    ]
