# Generated by Django 5.1.1 on 2024-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_alter_client_email_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
