# Generated by Django 5.1.1 on 2024-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0006_alter_bass_brand_alter_guitar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
