# Generated by Django 5.1.1 on 2024-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0007_alter_bass_model_alter_guitar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(),
        ),
    ]
