# Generated by Django 5.1.1 on 2024-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0008_alter_bass_price_alter_guitar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bass',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
